name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./CICD_Learning_Api/CICD_Learning_Api.csproj

    - name: Build
      run: dotnet build ./CICD_Learning_Api/CICD_Learning_Api.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish ./CICD_Learning_Api/CICD_Learning_Api.csproj -c Release -o ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-build
        path: ./publish
